### ISSUE TITLE
balena app image build process broken due inaccessible wifi-connect package

### ISSUE THREAD

**Issue by mkol5222** [balena-io/wifi-connect#248]
I have noticed that after name/domain changes (Oct 30 2018), image build process breaks on inaccessible wifi-connect packages.

I had to replace recommended approach
RUN curl https://api.github.com/repos/resin-io/resin-wifi-connect/releases/latest -s \
    | grep -hoP 'browser_download_url": "\K.*rpi\.tar\.gz' \
    | xargs -n1 curl -Ls \
    | tar -xvz -C /usr/src/app/

By better downloading current version manually and use approach:
COPY wifi-connect-v4.2.1-linux-aarch64.tar.gz wifi-connect-v4.2.1-linux-aarch64.tar.gz
RUN tar xzvf  wifi-connect-v4.2.1-linux-aarch64.tar.gz -C /usr/src/app/

Is this issue known?

**Comment by majorz** [comment]
@mkol5222 thanks for the report, I will merge the PR which involves the company changes now.

You are right that the recommended approach can be improved. We should pin the WiFi Connect version used in the Dockerfile to the currently released version instead of using latest.

**Comment by majorz** [comment]
Still have not merged this due to some CI issues. This is the corresponding PR: https://github.com/balena-io/wifi-connect/pull/247

**Comment by icylabsDev** [comment]
Can we use ```https://api.github.com/repositories/37727198/releases/latest```? 

I get ```{
  "message": "Moved Permanently",
  "url": "https://api.github.com/repositories/37727198/releases/latest",
  "documentation_url": "https://developer.github.com/v3/#http-redirects"
}``` from the curl call.

**Comment by majorz** [comment]
That should translate to `https://api.github.com/repos/balena-io/wifi-connect/releases/latest`.

**Comment by mkol5222** [comment]
Many thanks. I confirm that updating Dockerfile with URL https://api.github.com/repos/balena-io/wifi-connect/releases/lates fixed the problem and app build is progressing as expected.
I consider this solved by knowing right URL to use (documentation issue, not code issue).
