### ISSUE TITLE
Failed to run on Artik 530s

### ISSUE THREAD

**Issue by andrewjaykeller** [balena-io/wifi-connect#255]
```
Starting WiFi Connect
Cannot get the NetworkManager service state
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: D-Bus error: Failed to connect to socket /host/run/dbus/system_bus_socket: No such file or directory (org.freedesktop.DBus.Error.FileNotFound)', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by imrehg** [comment]
Hey @andrewjaykeller, are you running this repo directly, or adjusting to your own project? From the error it looks like it might be run in a service without the `io.balena.features.dbus` label being applied (hence not being able to talk to the system dbus https://www.balena.io/docs/reference/supervisor/docker-compose/#labels

Could you give a bit more context for our debugging and possible reproduction?

**Comment by andrewjaykeller** [comment]
Hi i'm using this repo directly and running with the following script:

```bash
#!/bin/bash

# Start balena-wifi-connect
export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

# Choose a condition for running WiFi Connect according to your use case:

# 1. Is there a default gateway?
# ip route | grep default

# 2. Is there Internet connectivity?
# nmcli -t g | grep full

# 3. Is there Internet connectivity via a google ping?
# wget --spider http://google.com 2>&1

# 4. Is there an active WiFi connection? 

start_wifi_connect=true

for _ in {1..30}
do
    iwgetid -r
    if [ $? -eq 0 ]; then
        start_wifi_connect=false
        break
    fi
    sleep 1s
done

if $start_wifi_connect; then
    printf 'Starting WiFi Connect\n'
    ./wifi-connect
else
    printf 'Skipping WiFi Connect\n'
fi

if [ "$HALT" == "1" ]; then
    echo "HALT don't do anything"
else
    npm start
fi
```

**Comment by imrehg** [comment]
That's weird, does `/host/run/dbus/system_bus_socket` exist in the application container? (if you connect to within the container, and run `ls -la /host/run/dbus/system_bus_socket`)

What version of the OS are you running this on? Is it deployed on balena-cloud, or is it an unmanaged / openBalena device?

**Comment by majorz** [comment]
@andrewjaykeller were you able to check for the existence of the D-Bus socket in the container?

**Comment by andrewjaykeller** [comment]
@imrehg and @majorz there is no /host/ directory

```bash
root@6949de9:/usr/src/app# ls -la /host/run/dbus/system_bus_socket
ls: cannot access '/host/run/dbus/system_bus_socket': No such file or directory
```

**Comment by majorz** [comment]
I assume you are using a multicontainer environment and the dbus label is missing. Please check this sample docker-compose.yml file for all the necessary settings to run WiFi Connect: https://github.com/balena-io-playground/wifi-connect-api/blob/master/docker-compose.yml

If everything is alright in this regard, then maybe it has to do with the base image in your Dockerfile.template of the wifi-connect container and you may post it here.

**Comment by andrewjaykeller** [comment]
@majorz no i certainly broke my wifi connect when i migrated to multi-container. I'm going to close this issue for now and will reopen if the issue persists.
