### ISSUE TITLE
balenaFin - not reconnecting to wifi after reboot

### ISSUE THREAD

**Issue by vvkhazan** [balena-io/wifi-connect#257]
Hi,

I'm using a balenaFin that's running balenaOS 2.29.2+rev1 in development mode. I deployed wifi-connect to it and everything works well -- I'm able to connect to the access point, configure the WiFi, and connect. However, after rebooting it does not automatically reconnect to the WiFi network I configured and I have to go through that process again.

I did not change any of the default configurations.

Thanks!

**Comment by majorz** [comment]
Hi @vvkhazan, there is a chance you are running into this issue: https://github.com/balena-os/meta-balena/issues/1376. Is there is a WiFi profile stored in the boot partition that targets the same network? Have you downloaded an image that you entered WiFi credentials in the dashboard for?

**Comment by vvkhazan** [comment]
Hi @majorz, I tried flashing a new image with ethernet only and production mode using the recommended version of balenaOS. Unfortunately the problem still persists. After a reboot, I'm seeing the following in the WiFi Connect service container logs:

```
29.01.19 12:42:32 (-0800) Service is already running 'main sha256:272e884f687ec7fba906174f87a02a28094e9d9d5818f392667332db7eea94cd'
29.01.19 12:43:57 (-0800)  main  User connected to the captive portal
29.01.19 12:44:08 (-0800)  main  Deleting existing WiFi connection: "MyWiFi"
29.01.19 12:44:08 (-0800)  main  Stopping access point 'WiFi Connect'...
29.01.19 12:44:10 (-0800)  main  Access point 'WiFi Connect' stopped
29.01.19 12:44:13 (-0800)  main  Access points: [...]
29.01.19 12:44:13 (-0800)  main  Connecting to access point 'MyWiFi'...
29.01.19 12:44:20 (-0800)  main  Internet connectivity established
```

So it looks like the existing connection profile is indeed getting deleted (maybe that happens because I'm trying to connect to the same one and it's overriding it when I input the credentials again?).

**Comment by vvkhazan** [comment]
That was it! Thanks for your help.
