### ISSUE TITLE
Use start.sh without Dockerfile?

### ISSUE THREAD

**Issue by charliesneath** [balena-io/wifi-connect#262]
I'm not sure how to trigger my `start.sh` file without running `wifi-connect` without balenaOS + Docker. Is this possible?

I would like to do something similar to the [`balena-wifi-connect-example`](https://github.com/balena-io-projects/balena-wifi-connect-example) and show visual feedback before and after connection to a network.

Right now, `wifi-connect` seems to run on start-up, which means I can't plug in to run my script if wifi isn't available.

**Comment by charliesneath** [comment]
@majorz After thinking about this more, a possible solution could be to provide an option to prevent `wifi-connect` from running when the device boots. 

That way, I could  create my own service to run `wifi-connect` via a customized script that handles the different wifi network states (connected, not connected, etc) and shows feedback.  

Please let me know if there’s a way to do this manually with the current version (without a Docker).

**Comment by charliesneath** [comment]
Closing this as I wrongfully assumed that `wifi-connect` automatically runs on boot, when this doesn't seem to be the case.

**Comment by charliesneath** [comment]
@majorz Is my understanding correct that the `wifi-connect` won't automatically run at boot unless programmed to do so?

**Comment by majorz** [comment]
This is correct.
