### ISSUE TITLE
Error: Cannot get the NetworkManager service state

### ISSUE THREAD

**Issue by charliesneath** [balena-io/wifi-connect#263]
I'm running the following code, which was working on a previous flash of my RPi Zero W's SD card. After re-imaging and re-installing, I'm not getting an error, where I expect `wifi-connect` to interrupt my correction wifi connection and create a portal.

`main.py:`

```
...

process = subprocess.Popen(['bash', 'wifi-connect.sh'])
process.wait()

...
```

`wifi-connect.sh:`

```
#!/usr/bin/env bash
export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
wifi-connect --portal-listening-port 45454
```

This is the error:

```
#!/usr/bin/env bash
Cannot get the NetworkManager service state
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: D-Bus error: Failed to connect to socket /host/run/dbus/system_bus_socket: No such file or directory (org.freedesktop.DBus.Error.FileNotFound)', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Expected behavior is that running this interrupts my current wifi connection, opens a portal, and let's me connect via the captive portal pop-up. This was working before but I can't identify what has changed to break this behavior, and show the error message instead.

**Comment by majorz** [comment]
You may check the `env` argument of `Popen` for specifying the environment variables to the run process and then run wifi-connect directly instead of through bash script.

The error is not related to this though. Are you running this in a multicontainer environment and is this on balenaOS? Can you paste me your dockerfile?

**Comment by charliesneath** [comment]
@majorz this is not running within a container environment, primarily because I’m currently unable to use the `rpi_ws281x` RGB LED library to control lights from within a container (see: https://github.com/jgarff/rpi_ws281x/issues/351).

I’m trying to figure out why it’s behaving differently now than before—is the expected behavior that it should interrupt current wifi connection and not throw an error?

**Comment by majorz** [comment]
If you are not running this under balenaOS then you should not export DBUS_SYSTEM_BUS_ADDRESS.

**Comment by charliesneath** [comment]
That fixed it, thank you!

**Comment by mowi22** [comment]
Hello, I'm attempting to do a multi-container environment. I am also getting this same error when running the wifi-connect start.sh. `Cannot get the NetworkManager service state`. 
This is my docker-compose
`version: '2'

services:
  wifi-connect:
    build: ./wifi-connect
    expose:
    - "80"

  gateway:
    build: ./gateway
    command: gateway:/mozilla-iot/gateway/run-app.sh
    image: mozillaiot/gateway:arm
    depends_on: 
      - wifi-connect
    ports:
      - "8080"



volumes:
  wifi-connect:
  gateway:

`
I also tried not exporting `DBUS_SYSTEM_BUS_ADDRESS` but I still have the same issue when i run `bash start.sh` in the service terminal.

**Comment by mafrmt00** [comment]
> Hello, I'm attempting to do a multi-container environment. I am also getting this same error when running the wifi-connect start.sh. `Cannot get the NetworkManager service state`.
> This is my docker-compose
> 
> `version: '2'
> 
> services:
> wifi-connect:
> build: ./wifi-connect
> expose:
> - "80"
> 
> gateway:
> build: ./gateway
> command: gateway:/mozilla-iot/gateway/run-app.sh
> image: mozillaiot/gateway:arm
> depends_on:
> - wifi-connect
> ports:
> - "8080"
> 
> volumes:
> wifi-connect:
> gateway:`
> 
> I also tried not exporting `DBUS_SYSTEM_BUS_ADDRESS` but I still have the same issue when I run `bash start.sh` in the service terminal.

You need to add the following to wifi-connect::

labels:
      io.balena.features.dbus: '1'
