### ISSUE TITLE
Redirect any browser web traffic to captive portal

### ISSUE THREAD

**Issue by charliesneath** [balena-io/wifi-connect#264]
Is there a way to configure `wifi-connect` to redirect any web requests in the browser to the captive portal login page?

**Comment by majorz** [comment]
Can you please elaborate more on the specifics of what you are trying to achieve as I do not understand well the question?

**Comment by charliesneath** [comment]
The use-case is that if someone were to connect to the wifi network but closed the captive portal. They could access the `wifi-connect` login via the browser using any URL since all traffic would be directed to the login page.

**Comment by majorz** [comment]
I am not sure whether I understand you correctly, but it looks like what you are looking for is the technique from the WiFi Connect's JSON API example project: https://github.com/balena-io-playground/wifi-connect-api/

**Comment by charliesneath** [comment]
Will this also redirect traffic from the web browser? My goal is to make sure that if someone were to close/dismiss the captive portal window, there would still be a way to enter the wifi credentials.

**Comment by majorz** [comment]
@charliesneath yes, you may modify the example project according to your use case without any issues. Basically it runs a web server on port 80, which is separate to the wifi-connect process that runs on another port, and you may adjust its behavior to your needs. It takes some time to get an understand of how to make a good use of it, but you should be all good with using the techniques there.
