### ISSUE TITLE
"Manifest not found" running curl - Debian "buster" release

### ISSUE THREAD

**Issue by pdcastro** [balena-io/wifi-connect#299]
The `Docker.template` file has this line:
```
FROM balenalib/%%RESIN_MACHINE_NAME%%-debian
```
and it thus appears that the wifi-connect project is affected by this issue:

Debian Buster arm32: "Manifest not found" using curl / TLS
https://github.com/balena-io-library/base-images/issues/562

**Known workarounds:**

* Replace the FROM line in the `Dockerfile.template` file with:
```
FROM balenalib/%%RESIN_MACHINE_NAME%%-debian:stretch
```
I.e., add "`:stretch`" to the end. This will revert to the previous Debian release.

* Alternatively, add "`RUN c_rehash`" after the package installation RUN instruction, as follows. This reportedly fixed another repo, allowing the new Debian "buster" release to be used.
```
FROM balenalib/%%RESIN_MACHINE_NAME%%-debian
RUN install_packages dnsmasq wireless-tools
RUN c_rehash
```

**Comment by majorz** [comment]
The issue has been resolved in our base images, so I am closing this one here as invalid.
