### ISSUE TITLE
cannot connect to SSID with trailing space

### ISSUE THREAD

**Issue by xginn8** [balena-io/wifi-connect#300]
When connecting to an SSID with a trailing space (such as "skynet "), wifi-connect fails to establish a connection and instead falls back to AP mode once again.

cc @majorz

**Comment by zrzka** [comment]
JS UI strips space at the end.

* `networks` request returns correct SSID - `"ssid":"skynet "`
* `connect` command receives incorrect SSID - `Incoming `connect` to access point `skynet` request`

Found the problem, can connect now:

```
wlan0     IEEE 802.11  ESSID:"skynet "  
          Mode:Managed  Frequency:5.5 GHz  Access Point: B4:18:D1:E1:B7:11   
          Bit Rate=150 Mb/s   Tx-Power=31 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:on
          Link Quality=70/70  Signal level=-40 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0
```
