### ISSUE TITLE
Send value from UI to Server

### ISSUE THREAD

**Issue by theruin0000** [balena-io/wifi-connect#305]
First, I have to say I'm a real noob in Rust

I want to send additional value to my Linux board when clicking the submit button.

So, I added input form in index.html easily but I wonder how to send it to the board

Actually, my board will do something with the delivered value after connecting with WiFi

Could you please help me about that?

Plus, how can I build the source?

Fortunately, I know how to use Docker

My Linux board's architecture is ARM 64, and the OS is Debian 9

**Comment by majorz** [comment]
We have an example of doing that through Python: https://github.com/balena-io-playground/wifi-connect-api/

**Comment by majorz** [comment]
Going to add some documentation now at the README of that repo.

**Comment by majorz** [comment]
I added additional information to the README. Please let me know if you have any questions.

**Comment by theruin0000** [comment]
@majorz 
Thank you so much! I'll try

**Comment by theruin0000** [comment]
@majorz 
I've tried several times but it doesn't work
It seems working fine but my phones and laptop could not find the AP(WiFi-connect)

>  * Serving Flask app "web-app" (lazy loading)
>  * Environment: production
>    WARNING: Do not use the development server in a production environment.
>    Use a production WSGI server instead.
>  * Debug mode: off
>  * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)


I did docker build/run as below
 docker build --tag wifi-connect .
 docker run -p 80:80 -p 45454:45454 wifi-connect

And, I had to change some words in Dockerfile.template as below
Because, these variables cannot found
 %%RESIN_MACHINE_NAME%%
 %%RESIN_ARCH%%

FROM balenalib/**generic-aarch64**-python:3.7.2-20190327

RUN curl -Ls https://github.com/resin-io/resin-wifi-connect/releases/download/$WW
IFI_CONNECT_VERSION/wifi-connect-$WIFI_CONNECT_VERSION-linux-**aarch64**.tar.gz | taa
r -xvz -C /tmp/download

**Comment by majorz** [comment]
@theruin0000 Docker will need `--cap-add=NET_ADMIN` (or `--privileged`) and `--network=host`, as those are required by dnsmasq.

Additionally you will need to mount the DBus socket in Docker. I need to look up how that is done on non-balenaOS environment.

Do you actually need Docker? Probably the best way is to download wifi-connect and put it in `/usr/local/sbin` on the OS directly. And follow the other steps from the Dockerfile.template but apply them on the OS. What do you think?

**Comment by theruin0000** [comment]
Do you mean following Dockerfile.template step by step manually?

Okay, I'll try :)

**Comment by majorz** [comment]
Yes, it is only a few steps like download and copy wifi-connect, clone the repo, install Python requirements, and run the application.

**Comment by theruin0000** [comment]
@majorz 
I just found it works well :)
So thanks for your help!
