### ISSUE TITLE
Support Debian 10 (buster)?

### ISSUE THREAD

**Issue by joeelia** [balena-io/wifi-connect#306]
I am using the latest Debian 10 (buster) lite image from Raspberry Pi Foundation. When trying to install this package I get an error:

`WiFi Connect Raspbian Installer: Distribution not based on Debian 9 (stretch)`

When I remove the check_os_version from main() function then the script installs, but the expected end result showing SSID doesn't work.

Does this package work with Debian 10 (buster)?

**Comment by majorz** [comment]
The application should work on Debian Buster. We need to update the installer. After you install the application what results does `nmcli d wifi` returns?

**Comment by bencharp** [comment]
in `check_os_version` I replace `Debian 9 (stretch)` by `Debian 10 (buster)`

```
if [ "$_version" != "10 (buster)" ]; then
        err "Distribution not based on Debian 10 (buster)"
fi
```
- Installation script fine
- SSID's list returned by `nmcli d wifi` is fine

it seems working fine on Debian Buster
