### ISSUE TITLE
Error trying to install on last Raspbian version

### ISSUE THREAD

**Issue by marcoscv-work** [balena-io/wifi-connect#314]
Error trying to install on last Raspbian version:

`WiFi Connect Raspbian Installer: Distribution not based on Debian 9 (stretch)`

![image](https://user-images.githubusercontent.com/7963804/66939624-b912c180-f043-11e9-9889-846a2d3ab9b4.png)

**Comment by davidwagnerkc** [comment]
I removed the Debian 9 Stretch check yesterday here: https://github.com/balena-io/wifi-connect/blob/4be6dd3297195f1e7145fb50bc6e064fb40845ee/scripts/raspbian-install.sh#L72

And Wifi-Connect worked on the Raspberry Pi 3B and 4 on Buster.
