### ISSUE TITLE
Duplicate SSIDs

### ISSUE THREAD

**Issue by marclennox** [balena-io/wifi-connect#331]
In the list of available WiFi networks, I always have a lot of duplicates.  I have 5 Google WiFi access points so I suspect that is the reason for the SSID duplication.  I also see a number of duplicates when I do a

`nmcli device wifi list`

Would it be possible to add a CLI option to collapse duplicate SSID names into a single dropdown entry?

**Comment by marclennox** [comment]
Alternatively, would you be open to a CLI option that would allow me to provide the list of SSIDs to use in the dropdown picklist instead of scanning?

This way I could use nmcli and remove duplicates.  It would also allow me to filter out SSIDs that I don't want to show.

**Comment by majorz** [comment]
There was recently a PR for removing duplicates here, but was never completed. I will try to get it done in the next days: https://github.com/balena-io/wifi-connect/pull/318

**Comment by MartinStuhl** [comment]
I have also the same issue with dublicate SSID showing.. It would be nice if you could change this!

**Comment by haigcd** [comment]
For me, the duplicates are not just distracting, they actually prevent me from using the system. It looks like multiple instances of the AP are selected, and I receive errors trying to submit. 

This is the first time I'm using wifi-connect, though, so please let me know if I'm doing something wrong.

![image](https://user-images.githubusercontent.com/64273216/80232549-13a85e00-8623-11ea-9e39-6a0f900729bb.png)

![image](https://user-images.githubusercontent.com/64273216/80232715-579b6300-8623-11ea-8f02-ac4a87279f08.png)

**Comment by silvermind** [comment]
@majorz any updates on this yet?

**Comment by violuke** [comment]
This is also broken for me as per @haigcd, any update?

**Comment by majorz** [comment]
Sorry for the big delay on this. Small PR added, which should be merged soon: #339.
