### ISSUE TITLE
Doesn't start on boot?

### ISSUE THREAD

**Issue by SketchThis** [balena-io/wifi-connect#332]
Hi there! I've got a Pi 4 that I have setup Wifi Connect on. I've gotten it to work fine from the command line... I can get the captive portal, connect the Pi to an available wifi network just fine.

Before I deploy this on my other Pis, I did a test:

I ran Wifi-connect and connected to a network. I then shut off that network to see if the captive portal came back. It didn't. I rebooted the Pi and the captive portal still didn't come back.

Should it have? I'd love to be able to use this to be able to run headless Pi's wherever I want...

**Comment by masterix21** [comment]
Hi, 

see it:
https://planb.nicecupoftea.org/2019/01/11/balenas-wifi-connect-easy-wifi-for-raspberry-pis/

**Comment by SketchThis** [comment]
That looks like exactly what I need. THANK YOU!
