### ISSUE TITLE
can't connect to open network

### ISSUE THREAD

**Issue by adam-larson-lee** [balena-io/wifi-connect#343]
I've tried connecting to one of our open (no passphrase) guest networks and this error popped up in the logs:

`14.07.20 16:45:52 (-0500)  wifi  [wifi_connect::server:ERROR] 'passphrase' not found in request params: {"identity": "", "ssid": "ARC Guest"}`

Looks like the endpoint is enforcing it in request parameters. Can it be optional, please?

**Comment by xginn8** [comment]
@adam-larson-lee let me know if you have any further trouble connecting to open networks. closing this issue for now
